name: first_flutter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http:  ^0.12.0
  flutter_swiper: ^1.1.4
  dio: 1.0.13
  fluttertoast: ^2.2.3
  flutter_webview_plugin: "^0.3.0+2"
  shared_preferences: ^0.4.3
  permission_handler: ^2.1.2
  crypto: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
  - images/ic_head.png
  - images/ic_personal_background.png
  - images/ic_rightArrow.png
  - images/ic_logout.png
  - images/ic_setting.png
  - images/ic_back.png
  - images/ic_store_collect.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
